version: '3.5'


services:
  client-gateway:
    container_name: session-client-gateway
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.client_gateway
    image: session/client-gateway
    ports:
      - "0.0.0.0:8000:8000"

  ingest-manager:
    container_name: session-ingest-manager
    build:
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.ingest_manager
    image: session/ingest-manager
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "0.0.0.0:8001:8001"

  ingest:
    container_name: session-ingest
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.ingest
    image: session/ingest
    ports: 
      - "0.0.0.0:9991:9991"
      - "0.0.0.0:9992:9992"
    # volumes: 
    #   - ./ingest_server/nginx.config:/etc/nginx/nginx.conf

  stream-registry:
    container_name: sessin-stream-registry
    build: 
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.stream_registry
    image: session/stream-registry
    ports:
      - "0.0.0.0:8001:8001"

  registry-database:
    container_name: session-registry-db
    build: 
      context: ./
      dockerfile: ./dockerfiles/Dockerfile.registry_db
    image: session/registry-db
    ports: 
      - "0.0.0.0:27017:27017"

# volumes:
#   ingest_srever/nginx.config