#!/bin/bash

alias ll = 'ls -al'

alias tail_acc = 'tail --lines 10 /var/log/nginx/access.log'
alias tail_conf = 'tail --lines 42 /etc/nginx/nginx.conf'
alias tail_err = 'tail --lines 10 /var/log/nginx/error.log'
